apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
{{- if gt (.Values.replicaCount | int) 1 }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1 # hello pod anti-affinity ;)
      maxSurge: 1
{{- end }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
{{- if gt (.Values.replicaCount | int) 1 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              {{- /* this has to match `include "chart.selectorLabels" . ` */}}
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - {{ .Release.Name }}
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ include "chart.name" . }}
            topologyKey: kubernetes.io/hostname
{{- end }}
      imagePullSecrets:
        - name: {{ include "chart.fullname" . }}
      containers:
      - command:
        - /mutator
        args:
        - --image-pull-secret-name={{ include "chart.fullname" . }}
        - --image-pull-secret-namespace={{ .Release.Namespace }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: mutator
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics
        readinessProbe:
          httpGet:
            path: /readyz/
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "chart.fullname" . }}-tls
